// <auto-generated />
namespace GithubExtension.Security.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MergeDbs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeDbs));
        
        string IMigrationMetadata.Id
        {
            get { return "201603102159058_MergeDbs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
